### ISSUE TITLE
[Julia] Array Element is not matched during isa()

### ISSUE THREAD

**Issue by achen12** [achen12/julia-d4m#5]
See Test #1 in CombinationalArguements in NevadaTestingGround folder.

**Comment by achen12** [comment]
@jakebolewski
@tkelman

**Comment by tkelman** [comment]
See http://docs.julialang.org/en/release-0.4/manual/types/#man-parametric-types, this is a common point of confusion. Abstract type parameters don't mean what you might think they mean.

**Comment by achen12** [comment]
That makes more sense now!  Thanks!
